name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Update Formspree Key
        run: |
          sed -i "s/PLACEHOLDER_KEY/${{ secrets.FORMSPREE_KEY }}/g" index.html
      
      - name: Deploy
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add index.html
          git commit -m "Update Formspree key for deployment" || echo "No changes to commit"
          git push
