name: Deploy with Formspree Key

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Update Formspree Key
        run: |
          sed -i "s/PLACEHOLDER_KEY/${{ secrets.FORMSPREE_KEY }}/g" index.html
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Formspree key for deployment"
            git push
          fi
